name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Atau branch lain yang sesuai

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runner Ubuntu

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Membuat direktori dist untuk GitHub Pages
      - name: Setup GitHub Pages directory
        run: mkdir -p dist

      # Menyalin file dari halaman pages/, assets/, dan data/
      - name: Copy files to dist directory
        run: |
          cp -r pages/* dist/  # Menyalin file dari folder pages/
          cp -r assets/* dist/ # Menyalin file dari folder assets/
          cp -r data/* dist/   # Menyalin file dari folder data/
          cp index.html dist/

      # Deploy ke GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # Atur branch untuk GitHub Pages
          publish_dir: ./dist       # Folder yang berisi file yang akan dipublish
